//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18034
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Web.Extension.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MetadataResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MetadataResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Web.Extension.Resources.MetadataResources", typeof(MetadataResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Confirmation Token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_ConfirmationToken {
            get {
                return ResourceManager.GetString("Membership_ConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Create Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_CreateDate {
            get {
                return ResourceManager.GetString("Membership_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirmed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_IsConfirmed {
            get {
                return ResourceManager.GetString("Membership_IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Last Password Failure Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_LastPasswordFailureDate {
            get {
                return ResourceManager.GetString("Membership_LastPasswordFailureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_Password {
            get {
                return ResourceManager.GetString("Membership_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Changed Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_PasswordChangedDate {
            get {
                return ResourceManager.GetString("Membership_PasswordChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Failures Since Last Success과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_PasswordFailuresSinceLastSuccess {
            get {
                return ResourceManager.GetString("Membership_PasswordFailuresSinceLastSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Salt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_PasswordSalt {
            get {
                return ResourceManager.GetString("Membership_PasswordSalt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Verification Token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_PasswordVerificationToken {
            get {
                return ResourceManager.GetString("Membership_PasswordVerificationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password Verification Token Expiration Date과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_PasswordVerificationTokenExpirationDate {
            get {
                return ResourceManager.GetString("Membership_PasswordVerificationTokenExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Membership_UserId {
            get {
                return ResourceManager.GetString("Membership_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OAuthMembership_Provider {
            get {
                return ResourceManager.GetString("OAuthMembership_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OAuthMembership_ProviderUserId {
            get {
                return ResourceManager.GetString("OAuthMembership_ProviderUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OAuthMembership_UserId {
            get {
                return ResourceManager.GetString("OAuthMembership_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Secret과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OAuthToken_Secret {
            get {
                return ResourceManager.GetString("OAuthToken_Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Token과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OAuthToken_Token {
            get {
                return ResourceManager.GetString("OAuthToken_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Role_RoleId {
            get {
                return ResourceManager.GetString("Role_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RoleName과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Role_RoleName {
            get {
                return ResourceManager.GetString("Role_RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserProfile_UserId {
            get {
                return ResourceManager.GetString("UserProfile_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UserProfile_UserName {
            get {
                return ResourceManager.GetString("UserProfile_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role ID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UsersInRoles_RoleId {
            get {
                return ResourceManager.GetString("UsersInRoles_RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UsersInRoles_UserId {
            get {
                return ResourceManager.GetString("UsersInRoles_UserId", resourceCulture);
            }
        }
    }
}
