//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18034
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Web.Extension.Resources {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Web.Extension.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Database operation failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_DbFailure {
            get {
                return ResourceManager.GetString("Security_DbFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No user table found that has the name &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_FailedToFindUserTable {
            get {
                return ResourceManager.GetString("Security_FailedToFindUserTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The &quot;MySqlWebSecurity.InitializeDatabaseConnection&quot; method can be called only once.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_InitializeAlreadyCalled {
            get {
                return ResourceManager.GetString("Security_InitializeAlreadyCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must set the &quot;mySqlSecurityInheritedContextType&quot; in AppConfig.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_InitializeMustBeAssignContext {
            get {
                return ResourceManager.GetString("Security_InitializeMustBeAssignContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must call the &quot;MySqlWebSecurity.InitializeDatabaseConnection&quot; method before you call any other method of the &quot;MySqlWebSecurity&quot; class. This call should be placed in an Global.asax or _AppStart.cshtml file in the root of your site.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_InitializeMustBeCalledFirst {
            get {
                return ResourceManager.GetString("Security_InitializeMustBeCalledFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No account exists for &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_NoAccountFound {
            get {
                return ResourceManager.GetString("Security_NoAccountFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To call this method, the &quot;Membership.Provider&quot; property must be an instance of &quot;ExtendedMembershipProvider&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_NoExtendedMembershipProvider {
            get {
                return ResourceManager.GetString("Security_NoExtendedMembershipProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No user found was found that has the name &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Security_NoUserFound {
            get {
                return ResourceManager.GetString("Security_NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to store OAuth token to database.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleMembership_FailToStoreOAuthToken {
            get {
                return ResourceManager.GetString("SimpleMembership_FailToStoreOAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The membership password is too long. (Maximum length is 128 characters).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleMembership_PasswordTooLong {
            get {
                return ResourceManager.GetString("SimpleMembership_PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider unrecognized attribute: &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleMembership_ProviderUnrecognizedAttribute {
            get {
                return ResourceManager.GetString("SimpleMembership_ProviderUnrecognizedAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The role &quot;{0}&quot; cannot be deleted because there are still users in the role.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRoleProvder_RolePopulated {
            get {
                return ResourceManager.GetString("SimpleRoleProvder_RolePopulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User &quot;{0}&quot; is already in role &quot;{1}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRoleProvder_UserAlreadyInRole {
            get {
                return ResourceManager.GetString("SimpleRoleProvder_UserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User &quot;{0}&quot; is not in role &quot;{1}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRoleProvder_UserNotInRole {
            get {
                return ResourceManager.GetString("SimpleRoleProvder_UserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No role found that has the name &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRoleProvider_NoRoleFound {
            get {
                return ResourceManager.GetString("SimpleRoleProvider_NoRoleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Role &quot;{0}&quot; already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SimpleRoleProvider_RoleExists {
            get {
                return ResourceManager.GetString("SimpleRoleProvider_RoleExists", resourceCulture);
            }
        }
    }
}
