//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.18034
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySql.Web.Extension.Common {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySql.Web.Extension.Common.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Value cannot be null or an empty string.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be between {0} and {1}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_Between {
            get {
                return ResourceManager.GetString("Argument_Must_Be_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be a value from the &quot;{0}&quot; enumeration.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_Enum_Member {
            get {
                return ResourceManager.GetString("Argument_Must_Be_Enum_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be greater than {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_GreaterThan {
            get {
                return ResourceManager.GetString("Argument_Must_Be_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be greater than or equal to {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Argument_Must_Be_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be less than {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_LessThan {
            get {
                return ResourceManager.GetString("Argument_Must_Be_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value must be less than or equal to {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Argument_Must_Be_LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value cannot be an empty string. It must either be null or a non-empty string.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Argument_Must_Be_Null_Or_Non_Empty {
            get {
                return ResourceManager.GetString("Argument_Must_Be_Null_Or_Non_Empty", resourceCulture);
            }
        }
    }
}
